name: Handmatige Bot Builder & Starter

on:
  workflow_dispatch:
    inputs:
      bot_version:
        description: 'Versie van de bot'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Code ophalen
      uses: actions/checkout@v4

    - name: Map aanmaken en code kopiëren
      run: |
        mkdir -Force "C:\MijnTradingBot"
        xcopy . "C:\MijnTradingBot" /E /H /Y

    - name: De Echte Tradingbot opstarten
      run: |
        cd "C:\MijnTradingBot"
        Start-Process cmd -ArgumentList '/k', 'python main.py'
